name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main
    paths:
      - 'client/dist/**'
      - 'server/**'
      - '.github/workflows/main.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            cd
            rm -r sd1
            git clone https://github.com/colemaring/sd1.git
            cd sd1/server
            echo "GOOGLE_GEMINI_API_KEY=${{ secrets.GOOGLE_GEMINI_API_KEY }}" > .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "FLEET_MANAGER_SECRET=${{ secrets.FLEET_MANAGER_SECRET }}" >> .env
            npm i
            pm2 kill
            pm2 start server.js
